# paperless-ngx
# https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres-tika.yml
---
name: paper

networks:
  paper:
    name: paper
  proxy:
    name: proxy
    external: true

services:
  # redis broker
  paper-broker:
    container_name: paper-broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    environment:
      PGID: 568
      TZ: Europe/London
    volumes:
      - /mnt/nas/containers/paperless/redisdata:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      paper:
        aliases:
          - paper-broker
  # postgresql database
  paper-db:
    container_name: paper-db
    image: docker.io/library/postgres:16
    restart: unless-stopped
    environment:
      PGID: 568
      TZ: Europe/London
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD_FILE: /run/secrets/paper_dbpass
    volumes:
      - /mnt/nas/containers/paperless/pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      paper:
        aliases:
          - paper-db
    secrets:
      - paper_dbpass
  # gotenberg
  paper-gotenberg:
    container_name: paper-gotenberg
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      paper:
        aliases:
          - gotenberg
  # tika
  paper-tika:
    container_name: paper-tika
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    networks:
      paper:
        aliases:
          - tika
  # paperless-ngx webserver
  paper-webserver:
    depends_on:
      - paper-db
      - paper-broker
      - paper-gotenberg
      - paper-tika
    container_name: paper-webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    environment:
      PAPERLESS_ADMIN_USER: /run/secrets/paper_admin_user
      PAPERLESS_ADMIN_MAIL: /run/secrets/paper_admin_mail
      PAPERLESS_ADMIN_PASS: /run/secrets/paper_admin_pass
      PAPERLESS_DBHOST: paper-db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS_FILE: /run/secrets/paper_dbpass
      PAPERLESS_EMAIL_FROM: /run/secrets/paper_email_from
      PAPERLESS_EMAIL_HOST: /run/secrets/paper_email_host
      PAPERLESS_EMAIL_HOST_PASSWORD: /run/secrets/paper_email_host_password
      PAPERLESS_EMAIL_HOST_USER: /run/secrets/paper_email_host_user
      PAPERLESS_EMAIL_PORT: 587
      PAPERLESS_EMAIL_USE_TLS: True
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_OCR_USER_ARGS: '{"continue_on_soft_render_error": true}'
      PAPERLESS_REDIS: redis://paper-broker:6379
      PAPERLESS_SECRET_KEY: /run/secrets/paper_secret_key
      PAPERLESS_TIME_ZONE: Europe/London
      PAPERLESS_URL: https://paper.darren.gdn
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paper-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paper-tika:9998
      PGID: 568
      TZ: Europe/London
      USERMAP_GID: 568
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paper.rule=Host(`paper.darren.gdn`)"
      - "traefik.http.routers.paper.entrypoints=https"
      - "traefik.http.routers.paper.tls=true"
      - "traefik.http.services.paper.loadbalancer.server.port=8000"
    volumes:
      - /mnt/nas/containers/paperless/data:/usr/src/paperless/data
      - /mnt/nas/containers/paperless/media:/usr/src/paperless/media
      - /mnt/nas/paperless/export:/usr/src/paperless/export
      - /mnt/nas/paperless/consume:/usr/src/paperless/consume
      - /etc/localtime:/etc/localtime:ro
    networks:
      paper:
        aliases:
          - paper-webserver
      proxy:
        aliases:
          - paper-webserver
    secrets:
      - paper_admin_user
      - paper_admin_mail
      - paper_admin_pass
      - paper_dbpass
      - paper_email_from
      - paper_email_host
      - paper_email_host_password
      - paper_email_host_user
      - paper_secret_key

secrets:
  paper_admin_user:
    file: /mnt/nas/secrets/paperless/paper_admin_user
  paper_admin_mail:
    file: /mnt/nas/secrets/paperless/paper_admin_mail
  paper_admin_pass:
    file: /mnt/nas/secrets/paperless/paper_admin_pass
  paper_dbpass:
    file: /mnt/nas/secrets/paperless/paper_dbpass
  paper_email_from:
    file: /mnt/nas/secrets/paperless/paper_email_from
  paper_email_host:
    file: /mnt/nas/secrets/paperless/paper_email_host
  paper_email_host_password:
    file: /mnt/nas/secrets/paperless/paper_email_host_password
  paper_email_host_user:
    file: /mnt/nas/secrets/paperless/paper_email_from
  paper_secret_key:
    file: /mnt/nas/secrets/paperless/paper_secret_key
